my:
  name: forezp
  age: 12
# 指定程序启动端口号
server:
  port: 8085
  tomcat:
    max-swallow-size: 100MB # 最重要的是这一行
# 指定使用哪个环境配置文件
spring:
  profiles:
    active: test

# MySQL 时区相差14小时问题，加参数 &useTimezone=true&serverTimezone=GMT%2B8
# CST 的时区是一个很混乱的时区，在与 MySQL 协商会话时区时，Java 会误以为是 CST -0500，而非 CST +0800，
# 详见 一次 JDBC 与 MySQL 因 “CST” 时区协商误解导致时间差了 14小时的排错经历
  datasource:
    url: jdbc:p6spy:mysql://localhost:3306/self?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    hikari:
      # 连接池中维护的最小空闲连接数
      minimum-idle: 5
      # 最大池大小
      maximum-pool-size: 5
      # 允许连接在连接池中空闲的最长时间（以毫秒为单位）
      idle-timeout: 300000
      # 池中连接关闭后的最长生命周期（以毫秒为单位）
      max-lifetime: 1200000
      # 池返回的连接的默认自动提交
      auto-commit: true
      # 是客户端等待连接池连接的最大毫秒数
      connection-timeout: 20000

mybatis-plus:
  global-config:
    db-config:
      id-type: AUTO


