my:
  name: forezp
  age: 12
# 指定程序启动端口号
server:
  port: 8088
  tomcat:
    max-swallow-size: 100MB # 最重要的是这一行
# 指定使用哪个环境配置文件
spring:
  profiles:
    active: test
  kafka:
    template:
      default-topic: default_topic
    # 消费者配置
    consumer:
      # 消费者客户端Id
#      client-id: self-study-consumer
      autoCommitInterval: 1000
      # 当偏移量不存在时， 自动重置到最近的偏移
      auto-offset-reset: latest
      # 是否自动提交偏移量
      enable-auto-commit: true
      # key 序列化器
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      # value 序列化器
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # 默认消费组Id
      groupId: defaultConsumerGroup
      properties:
        # 消费请求超时时间
        request:
          timeout:
            ms: 40000
        # 消费会话超时时间(超过这个时间consumer没有发送心跳,就会触发rebalance操作)
        session:
          timeout:
            ms: 40000
        # 反序列化时，类型转换受信任的包
        spring:
          json:
            trusted:
              packages: '*'
#          deserializer:
#            value:
#              delegate:
#                class: org.springframework.kafka.support.serializer.JsonDeserializer
    # 生产者配置
    producer:
      # 生产这的客户端Id
#      client-id: self-study-producer
      # 应答级别:多少个分区副本备份完成时向生产者发送ack确认(可选0、1、all/-1)
      acks: 1
      # 批量大小
      batch-size: 16384
      # 生产端缓冲区大小
      buffer-memory: 33554432
      # Kafka提供的序列化和反序列化类
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        # 提交延时
        linger:
          ms: 0
      # 重试次数
      retries: 0
    bootstrap-servers: localhost:9092


  # MySQL 时区相差14小时问题，加参数 &useTimezone=true&serverTimezone=GMT%2B8
# CST 的时区是一个很混乱的时区，在与 MySQL 协商会话时区时，Java 会误以为是 CST -0500，而非 CST +0800，
# 详见 一次 JDBC 与 MySQL 因 “CST” 时区协商误解导致时间差了 14小时的排错经历
  datasource:
    url: jdbc:p6spy:mysql://localhost:3306/self?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    hikari:
      # 连接池中维护的最小空闲连接数
      minimum-idle: 5
      # 最大池大小
      maximum-pool-size: 5
      # 允许连接在连接池中空闲的最长时间（以毫秒为单位）
      idle-timeout: 300000
      # 池中连接关闭后的最长生命周期（以毫秒为单位）
      max-lifetime: 1200000
      # 池返回的连接的默认自动提交
      auto-commit: true
      # 是客户端等待连接池连接的最大毫秒数
      connection-timeout: 20000

mybatis-plus:
  global-config:
    db-config:
      id-type: AUTO

management:
  server:
    port: 9001
  endpoint:
    shutdown:
      enabled: true
    health:
      enabled: true
      show-details: always

# 日志文件配置
logging:
  config: classpath:log4j2.yml



